//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scratchy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\*.*")]
        public string RenderExportImage_Name {
            get {
                return ((string)(this["RenderExportImage_Name"]));
            }
            set {
                this["RenderExportImage_Name"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        public string TEST {
            get {
                return ((string)(this["TEST"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_ShowScratches {
            get {
                return ((bool)(this["View_ShowScratches"]));
            }
            set {
                this["View_ShowScratches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_ShowGrid {
            get {
                return ((bool)(this["View_ShowGrid"]));
            }
            set {
                this["View_ShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\*.NC")]
        public string RenderExportNC_Name {
            get {
                return ((string)(this["RenderExportNC_Name"]));
            }
            set {
                this["RenderExportNC_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G21 G90\r\nG1 F400")]
        public string NC_Prolog {
            get {
                return ((string)(this["NC_Prolog"]));
            }
            set {
                this["NC_Prolog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M2")]
        public string NC_Epilog {
            get {
                return ((string)(this["NC_Epilog"]));
            }
            set {
                this["NC_Epilog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\*.OFF")]
        public string SaveAsOFF_Name {
            get {
                return ((string)(this["SaveAsOFF_Name"]));
            }
            set {
                this["SaveAsOFF_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public decimal Common_ToolAngle {
            get {
                return ((decimal)(this["Common_ToolAngle"]));
            }
            set {
                this["Common_ToolAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Common_Type {
            get {
                return ((int)(this["Common_Type"]));
            }
            set {
                this["Common_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal Common_ViewingAngle {
            get {
                return ((decimal)(this["Common_ViewingAngle"]));
            }
            set {
                this["Common_ViewingAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal Common_LightingAngle {
            get {
                return ((decimal)(this["Common_LightingAngle"]));
            }
            set {
                this["Common_LightingAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public decimal Common_MovingAngle {
            get {
                return ((decimal)(this["Common_MovingAngle"]));
            }
            set {
                this["Common_MovingAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal NC_TravelHeight {
            get {
                return ((decimal)(this["NC_TravelHeight"]));
            }
            set {
                this["NC_TravelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2")]
        public decimal NC_ScratchingDepthMax {
            get {
                return ((decimal)(this["NC_ScratchingDepthMax"]));
            }
            set {
                this["NC_ScratchingDepthMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2")]
        public decimal NC_ScratchingDepthZero {
            get {
                return ((decimal)(this["NC_ScratchingDepthZero"]));
            }
            set {
                this["NC_ScratchingDepthZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal NC_ScratchingDepthAtHeight {
            get {
                return ((decimal)(this["NC_ScratchingDepthAtHeight"]));
            }
            set {
                this["NC_ScratchingDepthAtHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NC_ForceG1onNegZ {
            get {
                return ((bool)(this["NC_ForceG1onNegZ"]));
            }
            set {
                this["NC_ForceG1onNegZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NC_CompensateRadius {
            get {
                return ((bool)(this["NC_CompensateRadius"]));
            }
            set {
                this["NC_CompensateRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal Common_ScanningStepAngle {
            get {
                return ((decimal)(this["Common_ScanningStepAngle"]));
            }
            set {
                this["Common_ScanningStepAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public decimal Common_WorkingAreaX {
            get {
                return ((decimal)(this["Common_WorkingAreaX"]));
            }
            set {
                this["Common_WorkingAreaX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal Common_WorkingAreaY {
            get {
                return ((decimal)(this["Common_WorkingAreaY"]));
            }
            set {
                this["Common_WorkingAreaY"] = value;
            }
        }
    }
}
